repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # this is optional, use `pre-commit autoupdate` to get the latest rev!
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8 cheetahpyanalytics/ --indent-size=4 --select=F,E112,E113,E203,E304,E502,E702,E703,E71,E72,E731,W191,W6 --statistics -j4
        language: system
        always_run: true
        pass_filenames: false
      - id: pylint
        name: pylint
        entry: pylint cheetahpyanalytics/ --exit-zero
        language: system
        always_run: true
        pass_filenames: false

      # - id: mypy
      #   name: mypy
      #   entry: mypy cheetahpy/ # --check-untyped-defs # --warn-return-any
      #   language: system
      #   always_run: true
      #   pass_filenames: false
      - id: tests
        name: tests
        entry: env pytest tests
        language: system
        always_run: true
        pass_filenames: false
